"""Backward-compatible config exports.

Use `settings.py` for environment-backed settings, `model_catalog.py` for model
metadata, and `constants.py` for static option lists.
"""

from constants import CURRENCIES, HOTEL_STARS, TRAVEL_CLASSES
from model_catalog import (
    DEFAULT_JUDGE_MODEL,
    DEFAULT_LLM_MODEL,
    DEFAULT_LLM_PROVIDER,
    GOOGLE_MODELS,
    MODEL_COSTS,
    OPENAI_MODELS,
)
from settings import (
    API_BASE_URL,
    API_HOST,
    API_PORT,
    CHROMA_ROOT_DIR,
    CSC_API_KEY,
    DEFAULT_CURRENCY,
    DEFAULT_DAILY_EXPENSE,
    DEFAULT_STAY_NIGHTS,
    EMBEDDING_MODELS,
    EVALS_DIR,
    FRONTEND_ORIGINS,
    GOOGLE_API_KEY,
    KNOWLEDGE_BASE_DIR,
    LANGCHAIN_API_KEY,
    LANGCHAIN_PROJECT,
    LANGCHAIN_TRACING_V2,
    LOG_LEVEL,
    MAX_FLIGHT_RESULTS,
    MAX_HOTEL_RESULTS,
    MEMORY_DATABASE_URL,
    OPENAI_API_KEY,
    PROJECT_ROOT,
    RAG_BM25_WEIGHT,
    RAG_CHUNK_OVERLAP,
    RAG_CHUNK_SIZE,
    RAG_EMBEDDING_BATCH_SIZE,
    RAG_EMBEDDING_MAX_RETRIES,
    RAG_EVAL_DATASET_PATH,
    RAG_EVAL_OUTPUT_DIR,
    RAG_GOOGLE_EMBEDDING_BATCH_DELAY_SECONDS,
    RAG_TOP_K,
    RAG_VECTOR_WEIGHT,
    RAW_FLIGHT_CANDIDATES,
    REQUIRE_PERSISTENT_CHECKPOINTER,
    SERPAPI_API_KEY,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_SENDER_EMAIL,
    SMTP_SENDER_PASSWORD,
    SMTP_USE_TLS,
)
